---

- name: uWSGI instance
  include: uwsgi_instance.yml uwsgi_path={{ giscube_uwsgi_directory }}

- name: uWSGI apps
  include: uwsgi-apps.yml
  vars:
      group_name: "{{ group.name }}"
      group_path: "{{ group.path }}"
      group_iscgi: "{{ group.cgi|default(false) }}"
      group_islocal: "{{ group.local|default(false) }}"
      uwsgi_instance: "{{ giscube_uwsgi_directory }}"
  with_items: "{{ giscube_appsservers }}"
  loop_control:
      loop_var: group
