---

- name: create uwsgi fcgi application server directory
  file: path={{ giscube_apps_server_uwsgi_directory }}/fcgis-ondemand state=directory
      owner=www-data
      group=www-data
      mode=0755

- name: copy uwsgi fastcgi application server to uwsgi directory
  template:
        backup=yes
        src=data/uwsgi/fcgis-ondemand/{{ item }}.j2
        dest={{ giscube_apps_server_uwsgi_directory }}/fcgis-ondemand/{{ item }}
        owner=root
        group=root
        mode=0644
  with_items:
      - envvars
      - uwsgi_build.ini
      - uwsgi.ini

- name: copy uwsgi fastcgi application server to uwsgi directory
  template:
        backup=yes
        src=data/uwsgi/fcgis-ondemand/{{ item }}.j2
        dest={{ giscube_apps_server_uwsgi_directory }}/fcgis-ondemand/{{ item }}
        owner=root
        group=root
        mode=0755
  with_items:
      - uwsgi_socket_name.sh
      - uwsgi.sh

- name: install uwsgi for fcgis-ondemand
  pip:
    virtualenv={{ giscube_apps_server_uwsgi_directory }}/fcgis-ondemand/venv/
    name=uwsgi version=2.0.12
  environment:
    UWSGI_PROFILE: "{{ giscube_apps_server_uwsgi_directory }}/fcgis-ondemand/uwsgi_build.ini"
