---

- name: create uwsgi directory
  file: path={{ uwsgi_path }} state=directory
      owner=www-data
      group=www-data
      mode=0755

- name: copy uwsgi config files
  template:
      backup=yes
      src=data/uwsgi/{{ item.name }}.j2
      dest={{ uwsgi_path }}/{{ item.name }}
      owner=root
      group=root
      mode={{ item.mode }}
  with_items:
      - { name: 'envvars', mode: '0644' }
      - { name: 'uwsgi_build.ini', mode: '0644' }

- name: install uwsgi for python2
  pip:
      virtualenv_python=python2.7
      virtualenv={{ uwsgi_path }}/venv/
      name=uwsgi version=2.0.12
  environment:
      UWSGI_PROFILE: "{{ uwsgi_path }}/uwsgi_build.ini"

- name: install uwsgi for python3 Ubuntu Trusty
  pip:
      virtualenv_command="pyvenv-3.4"
      virtualenv={{ uwsgi_path }}/venv3/
      name=uwsgi version=2.0.12
  environment:
      UWSGI_PROFILE: "{{ uwsgi_path }}/uwsgi_build.ini"
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'

- name: install uwsgi for python3 Ubuntu Xenial
  pip:
      virtualenv_command="pyvenv-3.5"
      virtualenv={{ uwsgi_path }}/venv3/
      name=uwsgi version=2.0.12
  environment:
      UWSGI_PROFILE: "{{ uwsgi_path }}/uwsgi_build.ini"
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'
