---

- name: create uwsgi directory
  file: path={{ uwsgi_path }}/src state=directory
      owner=root
      group=root
      mode=0750

- name: copy uwsgi config files
  template:
      backup=yes
      src=data/uwsgi/{{ item.name }}.j2
      dest={{ uwsgi_path }}/{{ item.name }}
      owner=root
      group=root
      mode={{ item.mode }}
  with_items:
      - { name: 'envvars', mode: '0640' }
      - { name: 'uwsgi_build.ini', mode: '0640' }
      - { name: 'build.sh', mode: '0750' }

- name: build uwsgi
  command: "{{ uwsgi_path }}/build.sh"
  args:
    creates: "{{ uwsgi_path }}/src/uwsgi-{{ giscube_uwsgi_version }}/uwsgi"

- name: build list of python versions for uwsgi python plugin
  set_fact:
    python_versions: "{{ giscube_uwsgi_python_versions }}"

- name: add python 3.4 to build list
  block:
  - name: add python 3.4 to build list
    set_fact:
      python_versions: "{{ python_versions + [ '3.4' ] }}"
    when: not giscube_uwsgi_python_versions

  - name: build python 3.4 plugin as default python3 plugin
    include: uwsgi-plugin-python.yml python_version=3.4 plugin_name=python3

  - name: build python 3.4 plugin as default python plugin
    include: uwsgi-plugin-python.yml python_version=3.4 plugin_name=python

  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'

- name: add python 3.5 to build list
  block:
  - name: add python 3.5 to build list
    set_fact:
      python_versions: "{{ python_versions + [ '3.5' ] }}"
    when: not giscube_uwsgi_python_versions

  - name: build python 3.5 plugin as default python3 plugin
    include: uwsgi-plugin-python.yml python_version=3.5 plugin_name=python3

  - name: build python 3.5 plugin as default python plugin
    include: uwsgi-plugin-python.yml python_version=3.5 plugin_name=python

  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'

- name: add python 3.6 to build list
  block:
  - name: add python 3.6 to build list
    set_fact:
      python_versions: "{{ python_versions + [ '3.6' ] }}"
    when: not giscube_uwsgi_python_versions

  - name: build python 3.6 plugin as default python3 plugin
    include: uwsgi-plugin-python.yml python_version=3.6 plugin_name=python3

  - name: build python 3.6 plugin as default python plugin
    include: uwsgi-plugin-python.yml python_version=3.6 plugin_name=python

  when: ansible_distribution == 'Ubuntu' and (ansible_distribution_release in ['zesty', 'bionic'])

- name: add python 3.8 to build list
  block:
  - name: add python 3.8 to build list
    set_fact:
      python_versions: "{{ python_versions + [ '3.8' ] }}"
    when: not giscube_uwsgi_python_versions

  - name: build python 3.8 plugin as default python3 plugin
    include: uwsgi-plugin-python.yml python_version=3.8 plugin_name=python3

  - name: build python 3.8 plugin as default python plugin
    include: uwsgi-plugin-python.yml python_version=3.8 plugin_name=python

  when: ansible_distribution == 'Ubuntu' and (ansible_distribution_release in ['focal'])

- name: add python 3.10 to build list
  block:
  - name: add python 3.10 to build list
    set_fact:
      python_versions: "{{ python_versions + [ '3.10' ] }}"
    when: not giscube_uwsgi_python_versions

  - name: build python 3.10 plugin as default python3 plugin
    include: uwsgi-plugin-python.yml python_version=3.10 plugin_name=python3

  - name: build python 3.10 plugin as default python plugin
    include: uwsgi-plugin-python.yml python_version=3.10 plugin_name=python

  when: ansible_distribution == 'Ubuntu' and (ansible_distribution_release in ['jammy'])

- name: build python {{ item }} plugin for uwsgi
  include: uwsgi-plugin-python.yml python_version={{ item }}
  with_items: "{{ python_versions | default([]) }}"
